# Generated by Django 3.2.15 on 2024-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_scraped', '0003_auto_20210426_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='proposition name'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='scraped_id',
            field=models.CharField(max_length=1000, verbose_name='proposition identification number'),
        ),
    ]
